# Session 6

### Array indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [1]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([
              [1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]
              ])
print(a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [2]:
a.shape

(3, 4)

In [3]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
a[2 , 2]

11

In [5]:
a[ 1:  , 1:3 ]  # last is exclusive

array([[ 6,  7],
       [10, 11]])

In [6]:
a[2: , 1:5]

array([[10, 11, 12]])

In [ ]:
4
8

In [7]:
a[:2,3:]

array([[4],
       [8]])

A slice of an array is a view into the same data, so modifying it will modify the original array.

In [8]:
# print(a[0, 1])
print(a)
a[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a)
# print(a[0, 1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[77  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
change 10 to 20

In [9]:
a[2 , 1] = 20
a

array([[77,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 20, 11, 12]])

You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:

In [10]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [11]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
a.shape

(4, 3)

In [ ]:
a[ 1:3 ]

array([[4, 5, 6],
       [7, 8, 9]])

Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [14]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
# #                     # this returns a numpy array of Booleans of the same
# #                     # shape as a, where each slot of bool_idx tells
# #                     # whether that element of a is > 2.

print(bool_idx)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [15]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
# print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6]


In [16]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a[a < 5]

array([1, 2, 3, 4])

In [17]:
a[ a>6 ]

array([], dtype=int64)

In [ ]:
task

1- create array 2d   shape 3 , 4

2- print > 5

3-  print row 2 col 3

For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the documentation.

In [2]:
import numpy as np
# Create the following rank 2 array with shape (3, 4)
a = np.random.randint(2,25,(4,5))
print(a)

[[ 9 14  6  6  4]
 [16 12 10 15 19]
 [19  7 22 22 24]
 [20  2 24 10  2]]


In [ ]:
[22 22 24
 
 24 10 2]

In [4]:
a[2:,2:]

array([[22, 22, 24],
       [24, 10,  2]])

### Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [18]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [19]:
# Elementwise sum; both produce the array
# print(x + y)
print(np.add(x, y))

[[ 6  8]
 [10 12]]


In [20]:
# Elementwise difference; both produce the array
# print(x - y)
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]


In [22]:
# Elementwise product; both produce the array
# print(x * y)
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]


In [23]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
# print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


Task

1- create function takes two arrays  size of array (3,3)

2- print multiply two arrays

3- print subtract 2 arrays

4- return sub array size 2,2 from result of mutliply


In [25]:
def calc(l1,l2):
    print(np.multiply(l1,l2))
    print(np.subtract(l1,l2))

    m = np.multiply(l1,l2)

    return m[:2,:2]

arr1 = np.array([
                [1,2,3],
                [4,5,6],
                [7,8,9]
                ])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

result = calc(arr1,arr2) # Call function
result

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


array([[ 1,  4],
       [16, 25]])

In [26]:
import numpy as np

In [27]:
x = np.array([[1 ,2],[3 , 4]])
x

array([[1, 2],
       [3, 4]])

In [28]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [ ]:
# x = np.array([[1,2],[3,4]])
# y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])   # 9 * 11 + 10*12  = 99 + 120 = 219

print (v)
print(w)
# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

[ 9 10]
[11 12]
219
219


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [33]:
x = np.array([[1,2,3],[6,3,8],[8,3,4]])
print(x)
print(np.sum(x))        # Compute sum of all elements; prints
print(np.sum(x, axis=0))  # Compute sum of each column; prints
# print(np.sum(x, axis=1))  # Compute sum of each row; prints

[[1 2 3]
 [6 3 8]
 [8 3 4]]
38
[15  8 15]


In [ ]:
x=np.arange(1,7).reshape(2,3)
print(x)
np.sum(x,axis = 0)

[[1 2 3]
 [4 5 6]]


array([5, 7, 9])

In [ ]:
Task

create array with random int values  3*3

sum all every columns


In [41]:
cm = np.random.randint(1,10,(3,3))#.reshape(3,3)
cm

array([[1, 3, 6],
       [3, 9, 4],
       [2, 4, 7]])

In [43]:
np.random.randint(1,10,9).reshape(3,3)

array([[7, 9, 4],
       [2, 8, 8],
       [6, 4, 4]])

In [35]:
cm.sum(axis = 0)

array([14, 13, 10])

You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [44]:
print(x)
print("transpose\n",
        x.T
        )  # T is capital   Transpose

[[1 2 3]
 [6 3 8]
 [8 3 4]]
transpose
 [[1 6 8]
 [2 3 3]
 [3 8 4]]


In [45]:
v = np.array([[1,2,3]])
print( v )
print( "transpose\n", v.T   )

[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


 2 3 6 1 2 5

 n = 6

 sum = 19

 mean = sum / n    >> Average


In [47]:
x=np.arange(1,7)
x

array([1, 2, 3, 4, 5, 6])

In [48]:
n = len(x)
n

6

In [49]:
sum = np.sum(x)
sum

21

In [50]:
mean = sum / n
mean

3.5

In [51]:
np.mean(x)

3.5

In [52]:
x=np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.mean(x, axis = 0)  # mean over columns

array([2.5, 3.5, 4.5])

In [ ]:
np.median(x, axis = 0)

array([2.5, 3.5, 4.5])

In [53]:
np.min(x,axis=0)

array([1, 2, 3])

In [54]:
np.max(x,axis=0)

array([4, 5, 6])

## Exercise

calculate mean of array 4 * 3 with integr random



1- print  sum total array

2- print mean every columns

3- print median every columns

4- print min every columns



In [ ]:
x = np.array([
            [0,1,2,3,4],
            [5,6,7,8,9],
            [10,11,12,13,14],
            [15,16,17,18,19]
            ])
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

1-

In [ ]:
print(np.mean(x))

9.5


2-

In [ ]:
print(np.mean(x,axis = 0))

[ 7.5  8.5  9.5 10.5 11.5]


3-


In [ ]:
print(np.median(x,axis = 0))

[ 7.5  8.5  9.5 10.5 11.5]


## Reference & Credits:

The tutorial above is a combination of the code/instructions created by

Eng / Mahmoud Khorshed